C/project_advance_views/project_advance_views/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alterra/', include('web_alterra.urls'))
]

C/project_advance_views/web_alterra/urls.py
from django.urls import path
from . import views

app_name = 'web_alterra'
urlpatterns = [
    path('', views.home, name='home'),
    path('blog', views.blog, name='blog'),
    path('mentor', views.mentor, name='mentor'),
    path('mentee', views.mentee, name='mentee'),
    path('author', views.author, name='author'),
    path('content_blog', views.content_blog, name='content_blog'),
    path('save_new_content', views.save_new_content, name='save_new_content')
]

C/project_advance_views/web_alterra/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Mentor(models.Model):
    nama = models.CharField(max_length=200, default=None)
    jabatan = models.CharField(max_length=200, default=None)
    experience = models.IntegerField(default=0)
    quote = models.CharField(max_length=200, default=None)
    img_mentor_url = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.nama

class Mentee(models.Model):
    nama = models.CharField(max_length=200, default=None)
    quote = models.CharField(max_length=200, default=None)
    img_mentee_url = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.nama

class Blog(models.Model):
    img_blog_url = models.CharField(max_length=200, default=None)
    title = models.CharField(max_length=500, default=None)
    text_content = models.TextField(default=None)
    date_post = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.title

    

C/project_advance_views/web_alterra/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Mentor, Mentee, Blog


# Create your views here.
def home(request):
    return render(request, 'web_alterra/home.html', {})
def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'web_alterra/blog.html', {'blogs':blogs})
def mentee(request):
    mentees = Mentee.objects.all()
    return render(request, 'web_alterra/mentee.html', {'mentees': mentees,})
def mentor(request):
    mentors = Mentor.objects.all()
    return render(request, 'web_alterra/mentor.html', {'mentors': mentors,})
def author(request):
    return render(request, 'web_alterra/author.html', {})
def content_blog(request):
    return render(request, 'web_alterra/content_blog.html', {})

def save_new_content(request):
    img_blog_url = request.POST['img_blog_url']
    title = request.POST['title']
    text_content = request.POST['text_content']

    b = Blog(img_blog_url=img_blog_url,title=title, text_content=text_content)
    b.save()

    blogs = Blog.objects.all()
    return render(request,'web_alterra/blog.html', {'blogs': blogs}) 

    

C/project_advance_views/web_alterra/templates/web_alterra/author.html
{% load static %}
    {% include 'web_alterra/header.html' %}
        <div class="page1">
            <div class="container">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <img class="foto-author" src="{% static 'img/author/author.jpg' %}" alt="">
                        <h4>Lelianto Eko Pradana</h4>
                        <p><span>Please Write your summary</span>,
                                Lorem ipsum Dolor Sit Amet.
                                Lorem ipsum Dolor Sit Amet.
                                Lorem ipsum Dolor Sit Amet.
                                Lorem ipsum Dolor Sit Amet.
                                Lorem ipsum Dolor Sit Amet.
                                Lorem ipsum Dolor Sit Amet.
                                
                        </p>
                        <table>
                                <tr>
                                    <td>Address</td>
                                    <td class="tab">: Jalan Flamboyan, Tidar, Malang</td>
                                </tr>
                                <tr>
                                    <td>Telephone </td>
                                    <td class="tab">: 081524235787</td>
                                </tr>
                                <tr>
                                    <td>Education</td>
                                    <td class="tab">: Sarjana</td>
                                </tr>
                                <tr>
                                    <td>Profession</td>
                                    <td class="tab">: Full-Stack Engineer</td>
                                </tr>
                                <tr>
                                    <td>Nationality</td>
                                    <td class="tab">: Indonesian</td>
                                </tr>
                                <tr>
                                    <td>Company</td>
                                    <td class="tab">: Alterra</td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td class="tab">: lian@alterra.id</td>
                                </tr>
                                <tr>
                                    <td>Company Address</td>
                                    <td class="tab">: Sepulsa Lodge Malang</td>
                                </tr>
                        </table>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5588.0098159187555!2d112.61123450373901!3d-7.965881862349451!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7882865ded0697%3A0xa77fa961a7c4e4b7!2sSepulsa%20Lodge%20Malang!5e0!3m2!1sen!2sid!4v1575900592186!5m2!1sen!2sid" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
        </div>
        {% include 'web_alterra/footer.html' %}
    </body>
</html>

C/project_advance_views/web_alterra/templates/web_alterra/blog.html
{% load static %}
    {% include 'web_alterra/header.html' %}     
        <div class="tombol">
            <p class= "new_article">
                <a href="content_blog" >Submit New Article</a>
            </p>
        </div>
        <div class="container left-right-container">
            <div class="row">
                <div class="col-md-12 body-blog-content">

                {% for blog in blogs %}
                    <div class="body-blog-content-row">
                        <img src="{{blog.img_blog_url}}" alt="" class="blog-content-img">
                        <p>{{blog.date_post}}</p>
                        <div class="article-title">{{blog.title}}</div>
                        <div>
                        <article>
                            {{blog.text_content}}
                        </article>
                        </div>
                        <div><a href="">Baca Selengkapnya</a></div>
                    </div>
                {% endfor %}
                </div>    
            </div>    
        </div>                  
    </section>
    {% include 'web_alterra/footer.html' %}
</body>
</html>

C/project_advance_views/web_alterra/templates/web_alterra/content_blog.html
{% load static %}
    {% include 'web_alterra/header.html' %}
    <div class="container" >
        <form action="{% url 'web_alterra:save_new_content'%}" method="POST">
                {% csrf_token %}
                <div>
                    <p>
                        <label for="img_blog_url">Masukkan Link Gambar:</label>
                        <br>
                        <input type="text" id="img_blog_url" name="img_blog_url" placeholder="www.link.com" required />
                    </p>
                    <p>
                        <label for="title">Masukkan Judul Artikel:</label>
                        <br>
                        <input type="text" id="title" name="title" placeholder="text title" required/>
                    </p>
                    <p>
                        <label for="text_content">Teks Artikel:</label>
                        <br>
                        <textarea id="text_content" name="text_content" cols="70" rows="10" required></textarea>          
                    </p>
                    <p>
                        <input type="submit" name="submit" value="Submit" />
                    </p>
                </div>

        </form>
    </div>
    <footer>
            <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 foot1">
                            <a>
                                Our Product:
                            </a>
                            <a href="">
                                <img class="img-f-1" src="{% static 'img/footer/logo-grey-alphapay.png' %}" />
                            </a>
                            <a href="">
                                <img class="img-f-2" src="{% static 'img/footer/logo-grey-sepulsa.png' %}" />
                            </a>
                            <a href="">
                                <img class="img-f-3" src="{% static 'img/footer/logo-grey-alphabill.png' %}" />
                            </a>
                        </div>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-7 foot2">
                            Contact Person: Mobile Phone: 0877 9609 9530. Email: 
                        </div>
                        <div class="col-md-5 foot3">
                            academy@alphatech.id
                        </div>
                    </div>
                </div>
    </footer>
</body>
</html>

C/project_advance_views/web_alterra/templates/web_alterra/footer.html
{% load static %}

<footer>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 foot1">
                    <a>
                        Our Product:
                    </a>
                    <a href="">
                        <img class="img-f-1" src="{% static 'img/footer/logo-grey-alphapay.png' %}" />
                    </a>
                    <a href="">
                        <img class="img-f-2" src="{% static 'img/footer/logo-grey-sepulsa.png' %}" />
                    </a>
                    <a href="">
                        <img class="img-f-3" src="{% static 'img/footer/logo-grey-alphabill.png' %}" />
                    </a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-7 foot2">
                    Contact Person: Mobile Phone: 0877 9609 9530. Email: 
                </div>
                <div class="col-md-5 foot3">
                    academy@alphatech.id
                </div>
            </div>
        </div>
    </footer>

C/project_advance_views/web_alterra/templates/web_alterra/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

<div class="blog-body">
        <header>
            <div class="container">
                <div class="row align-items-center blok-header">
                    <div class="col-md-6 align-items-center company-name">
                        Alpha Tech Academy
                    </div>
                    <div class="col-md-6">
                        <div class="header-nav">
                            <ul class="header-nav__list list-unstyled">  
                                <li> 
                                    <a href="/alterra">Home</a>
                                </li>
                                <li>
                                    <a href="blog" >Blog</a>
                                </li>
                                <li>
                                    <a href="mentor">Mentor</a>
                                </li>
                                <li>
                                    <a href="mentee">Mentee</a>
                                </li>
                                <li>
                                    <a href="author" >Author</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
    <div class="container-fluid left-right-container page-title-background">
        <div class="container page-title">
            <div class='company-logo'><img src="{% static 'img/title/alpha-logo.png' %}" alt="Gambar Logo"></div>
            <h1>Alpha Tech Academy Blog</h1>
            <p>Alpha Tech Academy is a tech talent incubator 
                that gives everyone (even non IT background) 
                a chance to be a professional Tech Talent within 3 months. 
                Contact Person : Email : academy@alphatech.id 
                Mobile phone: 0877 9609 9530</p>   
        </div>          
    </div>

C/project_advance_views/web_alterra/templates/web_alterra/home.html
{% load static %}
    {% include 'web_alterra/header.html' %}                 
        <div class="container home">
            <div class="row home-benefit align-items-center">
                <div class="col-md-4">
                    <div class="home-img">
                        <img src="{% static 'img/home/benefit.png' %}"/>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="home-benefit-text">
                        <h3>Learn awesome tech</h3>
                        <p>You will learn about programming languange, such as Python and Javascript, build 
                            back-end apps using Flask framework with microservice concept, build client-site 
                            apps using React Library etc.</p>
                    </div>
                </div>
            </div>
            <div class="row home-benefit align-items-center">
                <div class="col-md-4">
                    <div class="home-img">
                        <img src="{% static 'img/home/search-job.png' %}"/>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="home-benefit-text">
                        <h3>Land new job</h3>
                        <p>If you can pass this awesome program, you will be part of our reliable tech team for 
                            especially Software Engineer position and other tech position such as Quality 
                            Engineer, Sytem Analyst etc.</p>
                    </div>
                </div>
            </div>
            <div class="row home-benefit align-items-center">
                <div class="col-md-4">
                    <div class="home-img">
                        <img src="{% static 'img/home/get-paid.png' %}"/>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="home-benefit-text">
                        <h3>Get paid to learn</h3>
                        <p>Join for free and earn some money. Yes you read that right, no registration free
                            required to enter this program. To make things even better, you will recieve pocket 
                            money just for participating. Cool right?
                        </p>
                    </div>
                </div>
            </div>
            <div class="row home-desc">
                <div class="col-md-4 desc-img">
                    <div class="home-img">
                        <img src="{% static 'img/home/mission.png' %}"/>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="home-desc-text">
                        <div class="desc-who">
                            <h2>Who are we?</h2>
                            <p>Alpha Tech Academy is a tech talent incubation that gives anyone any chances (not 
                                even an IT background) to learn within 3 months of being a professional Tech Talent. 
                                What is our mission? We want to improve capability Tech Talent in Indonesia.
                            </p>
                        </div>
                        <div class="desc-what">
                            <h2>What is our mission?</h2>
                            <p>We want to improve capability Tech Talent in Indonesia</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row home-learn align-items-center">
                <div class="col-md-12">
                    <h2>What will you learn?</h2>
                </div>
            </div>
            <div class="row home-learn-icon align-items-center">
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-html.png' %}"/>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-programming.png' %}"/>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-git.png' %}"/>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-api.png' %}"/>
                    </div>
                </div>
            </div>
            <div class="row home-learn-icon align-items-center">
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-react.png' %}"/>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-tdd.png' %}"/>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-server.png' %}"/>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="home-icon">
                        <img src="{% static 'img/home/learn-scrum.png' %}"/>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% include 'web_alterra/footer.html' %}
    
</body>
</html>

C/project_advance_views/web_alterra/templates/web_alterra/mentee.html
{% load static %}
    {% include 'web_alterra/header.html' %}     
        <div class="container">
            <div class="row">
                <div class="col-md-12 mentee">
                    <h3>
                        Our Mentee
                    </h3>
                </div>
            </div>
        </div>

        {% for mentee in mentees %}
        <div class="container">
            <div class="row row_dist">
                <div class="col-md-3 img-men-1">
                    <a href="">
                        <img src="{% static 'img/mentee/' %}{{mentee.img_mentee_url}}" />
                    </a>
                </div>
                <div class="col-md-9 txt-men-1">
                    <h5>
                        {{mentee.nama}}
                    </h5>
                    <h6>
                        {{mentee.quote}}
                    </h6>
                </div>
            </div>
        </div>
        {% endfor %}
        
        {% include 'web_alterra/footer.html' %}
    </body>
</html>

C/project_advance_views/web_alterra/templates/web_alterra/mentor.html
{% load static %}
    {% include 'web_alterra/header.html' %}     
        <div class="container">
            <div class="row">
                <div class="col-md-12 mentee">
                    <h3>
                        Our Mentor
                    </h3>
                </div>
            </div>
        </div>

        {% for mentor in mentors %}
        <div class="container">
            <div class="row row_dist">
                <div class="col-md-3 img-men-1">
                    <a href="">
                        <img src="{% static 'img/mentor/' %}{{mentor.img_mentor_url}}" />
                    </a>
                </div>
                <div class="col-md-9 txt-men-1">
                    <h5>
                        {{mentor.nama}}
                    </h5>
                    <div class="jabatan">
                        {{mentor.jabatan}} ({{mentor.experience}} years experience)
                    </div>
                    <h6>
                        {{mentor.quote}}
                    </h6>
                </div>
            </div>
        </div>
        {% endfor %}
        {% include 'web_alterra/footer.html' %}
    </body>
</html>